### ISSUE TITLE
Memory leak in `add_reaction`

### ISSUE THREAD

**Issue by offlinemark** [TrueMemer/Crow#9]
`rest.c:add_reaction` creates a `req_t` but does not call `requests_close`, which will cause a memory leak every time this function is called.

https://github.com/TrueMemer/Crow/blob/579e1acd3becbb316497f07de64a58eb61d29232/src/rest.c#L109

p.s. cool to see you using librequests!! :)

**Comment by TrueMemer** [comment]
Thanks!
